import { MetadataRoute } from 'next'

// Used in development mode; production uses public/robots.txt generated by scripts/generate-robots.js
export const dynamic = 'force-static'

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_HOME_URL || 'https://fastgpt.io'
  const isCn = baseUrl.includes('.cn')

  // Block Googlebot on .cn domain to avoid duplicate content issues
  if (isCn) {
    return {
      rules: [
        {
          userAgent: 'Googlebot',
          disallow: '/'
        },
        {
          userAgent: '*',
          allow: '/'
        }
      ],
      sitemap: `${baseUrl}/sitemap.xml`,
      host: baseUrl
    }
  }

  // Block Baidu on .io domain to avoid duplicate content issues with .cn.
  // Bing is intentionally allowed because robots.txt cannot distinguish Bing China from global Bing.
  return {
    rules: [
      {
        userAgent: 'Baiduspider',
        disallow: '/'
      },
      {
        userAgent: '*',
        allow: '/'
      }
    ],
    sitemap: `${baseUrl}/sitemap.xml`,
    host: baseUrl
  }
}
