import { MetadataRoute } from 'next';
import { currentSiteBaseUrl } from '@/lib/siteRouting';

// Used in development mode; production uses public/robots.txt generated by scripts/generate-robots.js.
export const dynamic = 'force-static';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{ userAgent: '*', allow: '/' }],
    sitemap: `${currentSiteBaseUrl}/sitemap.xml`,
    host: currentSiteBaseUrl
  };
}
