import { MetadataRoute } from 'next';
import { currentSiteBaseUrl, currentSiteVariant, isPreviewSite } from '@/lib/siteRouting';

// Used in development mode; production uses public/robots.txt generated by scripts/generate-robots.js.
export const dynamic = 'force-static';

export default function robots(): MetadataRoute.Robots {
  if (isPreviewSite) {
    return { rules: [{ userAgent: '*', allow: '/' }] };
  }

  const sitemaps = [`${currentSiteBaseUrl}/sitemap.xml`];
  if (currentSiteVariant === 'cn') {
    sitemaps.push('https://fastgpt.cn/customers/sitemap.xml');
  }

  return {
    rules: [{ userAgent: '*', allow: '/' }],
    sitemap: sitemaps,
    host: currentSiteBaseUrl
  };
}
